Compare result endpoint
platiagro/projects pull request #187
Opened 2020-10-07 13:07 UTC by shiguemi32

2020-10-19 16:57 UTC, fberanizo requested changes
@shiguemi32, pode deixar tudo comparisons/comparisonId? pra ficar tudo igual..

2020-10-19 17:00 UTC, shiguemi32 commented
> @shiguemi32, pode deixar tudo comparisons/comparisonId? pra ficar tudo igual..

2020-10-19 17:00 UTC, shiguemi32 commented
> > @shiguemi32, pode deixar tudo comparisons/comparisonId? pra ficar tudo igual..

Ok

2020-10-21 11:11 UTC, fberanizo approved these changes

2020-10-21 11:11 UTC, merged