Feature - Predictions API
platiagro/projects pull request #214
Opened 2021-01-12 04:53 UTC by miguelfferraz

- Add Predictions API (projects/:projectId/deployments/:deploymentId/predictions)
- [POST] Create Prediction
- Add unit tests for Prediction API
- Add Swagger docs for Prediction API

2021-01-12 12:47 UTC, samborba reviewed
Consegui fazer o POST e a predição deu certo!!!

2021-01-12 12:47 UTC, samborba commented on projects/controllers/predictions.py
> +        raise BadRequest("`file` is required.")
@miguelfferraz acho que aqui não precisa das "template literals"

2021-01-12 14:25 UTC, fberanizo requested changes
@miguelfferraz gostei. O código ficou bem organizado, parabéns :)

Veja aqueles pontos que comentei, por favor.

2021-01-12 14:25 UTC, fberanizo commented on projects/controllers/predictions.py
> +    request = parse_csv_buffer_to_seldon_request(file)
@miguelfferraz a gente pode fazer upload de outros tipos de arquivos além do CSV.

Caso dê falha no parse, existem ainda esses formatos que o seldon aceita:
`{"strData": "plaintext"}` se o arquivo puder ser lido com `open('...', 'w')` 
`{"binData": "base64"}` se o arquivo puder ser lido com `open('...', 'wb')` 

Vja +- como tava no código do Alende:
https://github.com/platiagro/pipelines/pull/109/files#diff-4aff1cedf5e401cced007010d15a3669c6cc3743cfd215d664215bfdecc4dedcR76

2021-01-12 14:25 UTC, fberanizo commented on docs/swagger.yaml
> +                type: string
@miguelfferraz use aqui o `oneOf` para contemplar os 3 tipos de body:
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

`{"data":{"ndarray": [ ], "names": []}}`
`{"data":{"ndarray": [ ], "names": []}}`
`{"strData":"plainText"}`
`{"binData":"base64"}`

2021-01-12 14:25 UTC, fberanizo commented on docs/swagger.yaml
> +              example: []
@miguelfferraz veja se é possível deixar um object genérico já que todas as properties variam dependendo do model. Tem que procurar na OpenAPI...não sei se é possível. Caso não seja, pode deixar assim mesmo.

2021-01-13 14:52 UTC, fberanizo approved these changes
👍 :)

2021-01-13 14:53 UTC, merged