Feature/deployments watcher
platiagro/projects pull request #274
Opened 2021-04-26 12:41 UTC by miguelfferraz

Add status, url and deployed_at columns to the deployments table
This avoids fetching for this data in the kubernetes on each request.

Update deployment status on workflow watcher.
Add a new watcher for seldondeployments that will update deployment status.

2021-04-27 18:51 UTC, fberanizo requested changes
@miguelfferraz acho que precisa adicionar os novos campos ao swagger.yaml.

2021-04-27 18:51 UTC, fberanizo commented on projects/agent/watch_deployments.py
> +
Aqui deu um warning do flake8:
projects/agent/watch_deployments.py:82:1: W293 blank line contains whitespace

2021-04-27 18:51 UTC, fberanizo commented on projects/agent/watch_deployments.py
> +    session.commit()
@miguelfferraz uma coisa mais relacionada a convenção/padrão: 
nomes de módulos e pacotes geralmente a gente evita colocar `_`. 
https://www.python.org/dev/peps/pep-0008/#package-and-module-names

Talvez aqui pudesse ser algo assim: `agent/watchers/workflow.py` `agent/watchers/deployment.py`

2021-04-27 18:51 UTC, fberanizo commented on projects/controllers/deployments/deployments.py
> -        return deployments
🥰 🥰 🥰 🥰 🥰 🥰 🥰 🥰 🥰
Que felicidade em poder tirar essas linhas. haha

2021-04-27 18:51 UTC, fberanizo commented on projects/controllers/deployments/deployments.py
Tem esses 2 warnings do flake8 aqui:
projects/controllers/deployments/deployments.py:66:5: E303 too many blank lines (2)
projects/controllers/deployments/deployments.py:159:5: E303 too many blank lines (2)

2021-04-27 18:51 UTC, fberanizo commented on projects/agent/watch_workflows.py
> +        status = "Pending"
Não sei se era isso que vc pretendia nesse if, mas se `status = None`, dá false:
![image](https://user-images.githubusercontent.com/1791381/116294658-98661480-a76e-11eb-88c7-82aff15e503e.png)

2021-04-27 18:51 UTC, fberanizo commented on projects/agent/watch_workflows.py
> +        .update({"status": status, "deployed_at": deployed_at})
O atributo deployed_at é um DateTime, né? Olhando as linhas anteriores parece que o deployed_at é uma str. Não dá pra passar o datetime direto aqui? Aliás, dá certo passar str?

2021-04-27 18:51 UTC, fberanizo commented on projects/agent/watch_workflows.py
> +        created_at = datetime.strptime(created_at_str, "%Y-%m-%dT%H:%M:%SZ")
Acho que você já tinha usado uma vez o `dateutil.parser.isoparse` e achei legal (melhor que o strptime).
Que tal usar aqui?

2021-04-27 18:51 UTC, fberanizo commented on projects/agent/main.py
> +    sdeps_thread = threading.Thread(target=watch_seldon_deployments, args=(api, session))
@miguelfferraz , você não tava usando o asyncio e run_forever? Deu algo de errado? :X

2021-04-29 05:00 UTC, miguelfferraz commented on projects/agent/main.py
> +    sdeps_thread = threading.Thread(target=watch_seldon_deployments, args=(api, session))
Não descobri o motivo, mas não consegui usar os watcher com o run_forever. A solução que achei foi usar o threading mesmo.

2021-04-29 16:34 UTC, fberanizo approved these changes
👍

2021-04-29 16:34 UTC, merged