Adds readiness_probe_initial_delay_seconds to Task
platiagro/projects pull request #288
Opened 2021-05-05 21:12 UTC by fberanizo

Specifies how long should SeldonDeployment wait before readiness probes start.
Env variable DEPLOYMENT_INIT_TIMEOUT was removed and replaced by
TASK_DEFAULT_READINESS_INITIAL_DELAY_SECONDS + 60 seconds.

2021-05-26 00:33 UTC, fberanizo commented
@miguelfferraz acabei mexendo em várias coisas neste PR :x
- Consertei alguns unittests.
- Corrigi um bug (retorno vazio) ao editar experimento usando template
- Tentei corrigir o problema de gerar notebook com mountPath repetido (quebrando o Jupyter).
- Além da ideia original da tarefa que é permitir configurar o `readiness_probe_initial_delay_seconds` (o seldon define uma conf padrão de liveness probe e se em 35s não terminar o `def __init __(self)` do Model.py ele reinicia o pod). Tem tarefas que demoram mais que isso. Alias, depois deste PR tem que adicionar essa conf lá no repo tasks.

Dá uma olhada, por favor, quando puder. :)

2021-05-26 14:43 UTC, fberanizo commented on projects/kfp/templates.py
> +                },
@miguelfferraz @dnlcesilva @andreluiz27 isso aqui é interessante que vocês aprenderem sobre o Kubernetes.
Todo container pode definir `livenessProbe` e `readinessProbe`.
O `livenessProbe` é um check de tempos em tempos pra ver se o container está rodando, não travou etc... Se ele falhar o kubernetes reinicia o container.
O `readinessProbe` é um check que define se o container está Ready/Running. Se ele falhar, o kubernetes também reinicia o container.

Neste caso aqui são probes pros fluxos implantados, que são serviços REST.  Então o probe é um ping numa porta com nome "http".

![image](https://user-images.githubusercontent.com/1791381/119680430-8e8c0b80-be17-11eb-927d-a20fcadb0cae.png)

2021-05-26 15:19 UTC, fberanizo commented on projects/kubernetes/notebook.py
> +            return
@miguelfferraz as alterações neste arquivo podem ajudar com erros no delete e no update, mas no create nada mudou.
Antes a gente checava se o pod tinha o volume a ser deletado/alterado, mas como as alterações são feitas no (custom resource do) notebook, e leva um tempo pro pod e o notebook sincronizarem, tinha a chance de dar erro.

Bem...a gente já viu erros no create também (criar 2 tarefas com o mesmo mountPath). Faz sentido fazer um `get_namespaced_custom_object` para checar se o volume já existe antes dar um add?

2021-05-31 18:45 UTC, miguelfferraz requested changes

2021-06-01 21:54 UTC, merged