New fields The Task API.
platiagro/projects pull request #303
Opened 2021-06-11 13:00 UTC by dnlcesilva

2021-06-15 15:00 UTC, fberanizo requested changes
@dnlcesilva obrigado! Deu trabalho pra rodar os testes, mas ficou 100.0% Coverage, que é excelente. :)

---

Precisamos fazer mais algumas alterações, pra ajudar o @LuanEdCosta lá no frontend diferenciar entre tarefas que usam notebook e tarefas que não usam notebook:

no model.Task adicione, por favor uma `hybrid_property` (que é um atributo de model que não está no BD, e é computado por uma função):
```python
from sqlalchemy.ext.hybrid import hybrid_property
class Task(Base):
...
    @hybrid_property
    def has_notebook(self):
        return self.experiment_notebook_path or self.deployment_notebook_path
```
Adicione também ao schemas.Task o atributo `has_notebook: bool` (e na função  `def from_orm(cls, model):`

---

A 2a alteração é neste trecho de código:
https://github.com/platiagro/projects/blob/fafaccf37599ecfb389f05588727d478ca26da12/projects/controllers/tasks/tasks.py#L191-L212

Ao criar uma tarefa, se `task.image is not None` então `experiment_notebook_path`, `deployment_notebook_path`, `task.experiment_notebook`, `task.deployment_notebook` devem ser `None` (porque o `task.image` indica que é uma tarefa que não tem notebooks). 

---

A última alteração é adicionar `image`, `cpu_limit`, `cpu_request`, `memory_limit`, `memory_request`, `readiness_probe_initial_delay_seconds` ao schema.Task para serem retornados também (não se esqueça de adicioná-los no `from_orm` nessa mesma classe:
https://github.com/platiagro/projects/blob/fafaccf37599ecfb389f05588727d478ca26da12/projects/schemas/task.py#L65-L78

Ah, adicione-os no swagger.yaml também, por favor.

2021-06-15 15:15 UTC, andreluiz27 commented on tests/test_tasks.py
> +            "category": "DEFAULT",
Eu fiquei com uma simples dúvida, em todos você colocou "category:" CATEGORY, constante que você declarou no começo do código, entretanto, nesse trecho você não utiliza a constante

2021-06-15 20:53 UTC, fberanizo commented on projects/controllers/tasks/tasks.py
> +            valid_str = ",".join(VALID_CATEGORIES)
@dnlcesilva não se esqueça de trocar este if aqui também (pra ficar igual ao update_tasks).

2021-06-17 00:48 UTC, fberanizo approved these changes
👍

2021-06-17 01:24 UTC, merged