Uses Header 'kubeflow-userid' as a filter for DB operations
platiagro/projects pull request #321
Opened 2021-07-03 22:36 UTC by fberanizo

Proof-of-concept for a multittenant API.

2021-07-06 13:58 UTC, fberanizo commented on docs/swagger.yaml
> +  - ApiKeyAuth: []
@miguelfferraz não sei se essa é a melhor maneira de documentar no Swagger. Aliás, a chave é opcional.
Fiz assim pq não queria adicionar header em todas as URL :x

2021-07-06 14:24 UTC, fberanizo commented
@miguelfferraz @andreluiz27 Explicando o que fiz aqui:
Nos ambientes com login o browser manda um cookie que identifica o usuario.
O Istio (que age como o "proxy" que intercepta as requisições pra plataforma)  usa o Cookie para autenticar o usuário e manda pro backend um header `"kubeflow-userid: usuario"`

Aqui neste PR eu uso o usuario como uma nova coluna das tabelas projects e templates. 

Diferentes usuários verão diferentes projetos, templates e "filhos" (experimentos, deployments, operators...).
*As tarefas são as mesmas para todos usuários.* Fiz assim porque a tarefa está atrelada ao Jupyter e criar namespaces diferentes aumentaria muito a complexidade em um momento que não temos tempo para isso.

Os workflows continuam sendo rodados no namespace anonymous para todos usuários.

---
O que vocês acham que dá pra fazer diferente...pensando em algo entregável neste mês?

2021-07-06 16:03 UTC, andreluiz27 reviewed
Fábio, deixa eu ver se entendi:

Você pega um cookie do tipo header e instancia como um objeto do tipo fastapi.header, e passa isto como argumentos dos controllers ProjectController e DeploymentsController, e com isto você utiliza para eventuais filtros em query no BD através do campo Tenant. Mas aí ficou uma dúvida:

O que acontece se a pessoa tiver um ID que não existe nos cookies ? 

Talvez caberia uma exceção ?

2021-07-06 16:11 UTC, andreluiz27 commented on projects/models/template.py
> +    tenant = Column(String(255), nullable=True)
Ficou um tenant pra cada modelo ? O que isto leva em vantagem em relação a fazer uma entidade chamada User/Tenant, e essa entidade servir uma chave externa pra diversos modelos ?

2021-07-06 16:12 UTC, andreluiz27 commented
> @miguelfferraz @andreluiz27 @dnlcesilva Explicando o que fiz aqui:
> Nos ambientes com login o browser manda um cookie que identifica o usuario.
> O Istio (que age como o "proxy" que intercepta as requisições pra plataforma) usa o Cookie para autenticar o usuário e manda pro backend um header `"kubeflow-userid: usuario"`
> 
> Aqui neste PR eu uso o usuario como uma nova coluna das tabelas projects e templates.
> 
> Diferentes usuários verão diferentes projetos, templates e "filhos" (experimentos, deployments, operators...).
> _As tarefas são as mesmas para todos usuários._ Fiz assim porque a tarefa está atrelada ao Jupyter e criar namespaces diferentes aumentaria muito a complexidade em um momento que não temos tempo para isso.
> 
> Os workflows continuam sendo rodados no namespace anonymous para todos usuários.
> 
> O que vocês acham que dá pra fazer diferente...pensando em algo entregável neste mês?

2021-07-06 16:31 UTC, andreluiz27 commented on projects/models/project.py
> +    tenant = Column(String(255), nullable=True)
Caberia aqui uma restrição de unicidade ?

2021-07-07 12:40 UTC, andreluiz27 requested changes
Os comentários que fiz eram mais curiosidades que tive. Todavia, entendo da urgência dessa feature, a mudança que ficaria legal nesse código seria uma adição de uma exceção caso o kuberuserid não seja encontrado no BD, i.e, se o tenant não existir. Caso por ventura haja essa exceção e eu não tenha visto a implementação peço então que ignore o "Request changes" deste Pull Request

2021-07-07 12:51 UTC, fberanizo commented on projects/models/template.py
> +    tenant = Column(String(255), nullable=True)
Oi! Aqui a ideia é parecida com o que você falou, sim. 
O `tenant` é uma coluna que identifica que o template (ou projeto) pertence àquele tenant. 
Porém,  a diferença é não existe a tabela de User/Tenant. A responsabilidade de lidar com cadastro  e autenticação de usuários não fica aqui neste serviço. Quem lida com isso é o Istio / Dex : https://github.com/platiagro/manifests/tree/v0.2.0-kubeflow-v1.3-branch/contrib/dex-auth

e aqui não faz diferença se o tenant existe ou não; eu simplesmente pego o valor do header e faço o `where tenant = 'valor-do-header'`

2021-07-07 12:53 UTC, fberanizo commented on projects/models/project.py
> +    tenant = Column(String(255), nullable=True)
Como eu disse no outro comentário, o `tenant` é como uma chave estrangeira que identifica que o projeto / template pertence àquele tenant.
Podem existir vários projetos com um mesmo tenant, então acredito que não faz sentido chave única (senão cada usuário teria um único projeto.

2021-07-07 13:00 UTC, fberanizo commented
> Os comentários que fiz eram mais curiosidades que tive. Todavia, entendo da urgência dessa feature, a mudança que ficaria legal nesse código seria uma adição de uma exceção caso o kuberuserid não seja encontrado no BD, i.e, se o tenant não existir. Caso por ventura haja essa exceção e eu não tenha visto a implementação peço então que ignore o "Request changes" deste Pull Request

De fato não tem exceção aqui não. O serviço assume que tem alguém que já lidou com isso pra ele.
Tentei encontrar alguns links que explicam como isso funciona no kubeflow:
https://www.kubeflow.org/docs/components/multi-tenancy/design/
https://github.com/platiagro/manifests/tree/v0.2.0-kubeflow-v1.3-branch/contrib/dex-auth

Acho que tentam seguir alguns princípios de micro-serviços e delegam essa responsabilidade de autenticação de usuário para outro micro-serviço.
De qualquer forma, todos os registros estarem numa mesma tabela (como é o caso aqui) eu sei que não é uma boa prática.

2021-07-07 13:37 UTC, fberanizo commented
> Fábio, deixa eu ver se entendi:
> 
> Você pega um cookie do tipo header e instancia como um objeto do tipo fastapi.header, e passa isto como argumentos dos controllers ProjectController e DeploymentsController, e com isto você utiliza para eventuais filtros em query no BD através do campo Tenant. Mas aí ficou uma dúvida:
> 
> O que acontece se a pessoa tiver um ID que não existe no BD ?
> 
> Talvez caberia uma exceção ?

A parte que usa o cookie não fica aqui neste repo `projects`. 

Que lida com isso é Istio (proxy server/service mesh) e o Dex (serviço de autenticação OIDC). 
Os 2 são parte do Kubeflow e foram aproveitados aqui na PlatIA.

O pessoal do Kubeflow criou esta configuração para usar o cookie e autenticar:
https://github.com/platiagro/manifests/blob/91f8bce4b8be7aba99457c63f4b71c1320ab5148/common/oidc-authservice/base/envoy-filter.yaml#L25-L41

Explicando este arquivo:
É configurado com um "Filtro" que intercepta todas requisições pra plataforma e envia pra um `http_service` 
Além disso, é obrigatório que tenha um dos headers: cookie, authorization, ou x-auth-token.


```bash
            '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            http_service:
              server_uri:
                uri: http://$(AUTHSERVICE_SERVICE).$(AUTHSERVICE_NAMESPACE).svc.cluster.local
                cluster: outbound|8080||$(AUTHSERVICE_SERVICE).$(AUTHSERVICE_NAMESPACE).svc.cluster.local
                timeout: 10s
              authorization_request:
                allowed_headers:
                  patterns:
                    # XXX: MUST be lowercase!
                    - exact: "authorization"
                    - exact: "cookie"
                    - exact: "x-auth-token"
```

O mesmo filtro aí espera que o `http_service` retorne um header `kubeflow-userid`
```
allowed_upstream_headers:
  patterns:
  - exact: "kubeflow-userid"
```
---

## Agora falando sobre o serviço de autenticação

A gente configurou o Dex para usar uma autenticação com login / senha "estáticos":
https://github.com/platiagro/manifests/blob/v0.2.0-kubeflow-v1.3-branch/platiagro-auth/patches/dex-configmap.yaml

Existe este configmap do kubernetes que armazena os logins e hashes das senhas ^

Quando você deseja criar novos usuários tem que editar este configmap e reniciar o pod do dex.

2021-07-07 19:51 UTC, andreluiz27 commented on projects/models/template.py
> +    tenant = Column(String(255), nullable=True)
Ah, bacana, vou ler sobre o istio inclusive.

2021-07-07 19:55 UTC, andreluiz27 commented on projects/models/project.py
> +    tenant = Column(String(255), nullable=True)
Aah parei aqui pra pensar bem, faz sentido. Me baseei no padrão de tenant como uma tabela. Na maneira moldada realmente não faz sentido unicidade.

2021-07-07 20:07 UTC, andreluiz27 approved these changes
Depois de ler todos os comentários, entendi com maior profundida a dinâmica entre as requisições. Pelo que entendi há todo um processo para a obtenção do kubeflowuserid, e isto antecede o  código aqui em "projects". Tendo isto em vista, várias situações já são pré tratadas.

2021-07-08 15:50 UTC, merged