WIP:Fix/setting dependencies
platiagro/projects pull request #333
Opened 2021-07-29 16:37 UTC by andreluiz27

2021-07-30 14:44 UTC, fberanizo requested changes

2021-07-30 14:44 UTC, fberanizo commented on projects/controllers/deployments/deployments.py
> +            self.session.commit()
@andreluiz27 não é uma boa prática acionar `session.commit()` várias vezes em uma requisição.
Essa função `copy_operators` pode ser chamada várias vezes no `create_deployments`.

Se a API em algum momento lançar exceção, o commit vai salvar parte dos deployments.
Imagino que o comportamento correto é não salvar nada quando a API retornar erro 500.

Será que um session flush não resolve aí o que você quer fazer?
https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.Session.flush

2021-07-30 18:47 UTC, andreluiz27 commented on projects/controllers/deployments/deployments.py
> +            self.session.commit()
Então, eu tive que colocar o session.commit() pois o filter_by.(uuid=uiid_do_operador_criado).update não estava funcionando. Mas confesso que me questionei da possibilidade que você listou, fico feliz em saber que existe o sessiom.flush(), li sobre e faz realmente o que eu preciso, obrigado pela sugestão!

2021-08-03 20:38 UTC, fberanizo approved these changes
👍

2021-08-03 21:38 UTC, merged