Correcting copies of tasks.
platiagro/projects pull request #338
Opened 2021-08-20 12:59 UTC by dnlcesilva

Fixing copies of tasks, before copying task with name of "Tarefa em branco".

2021-08-23 12:25 UTC, fberanizo requested changes

2021-08-23 12:25 UTC, fberanizo commented on projects/controllers/tasks/tasks.py
> +            task.name = self.generate_name_task(stored_task.name + " - Cópia")
@dnlcesilva que tal trocar + por f-string: `f"{stored_task.name} - Cópia"`. 
A vantagem da f-string é relacionada a desempenho e facilidade de leitura.:
https://realpython.com/python-f-strings/#f-strings-a-new-and-improved-way-to-format-strings-in-python

Neste caso não faz diferença, já que é uma string pequena, mas é preferível utilizá-la sempre que possível.

2021-08-23 14:43 UTC, dnlcesilva commented on projects/controllers/tasks/tasks.py
> +        print(check_comp_name)
@fberanizo, esqueci vou retirar!

2021-08-24 19:05 UTC, andreluiz27 requested changes
Dei approve pois olhei e parece okay

2021-08-24 19:05 UTC, andreluiz27 commented on projects/controllers/tasks/tasks.py
> +    def task_category(self, task_cat):
Boa tarde Danilo, estava analisando seu código. Me parece adequado e coesivo, entretanto, talvez o nome da função task_category poderia ter um outro nome, talvez explicitando o que ela faz, talvez um raise_if_task_category_not_valid(self, task_cat) ou algo parecido

2021-08-24 19:15 UTC, dnlcesilva commented on projects/controllers/tasks/tasks.py
> +    def task_category(self, task_cat):
@andreluiz27 boa tarde, concordo com sua sugestão, obrigado!

2021-08-25 14:44 UTC, fberanizo requested changes
👍

2021-08-25 14:44 UTC, fberanizo approved these changes
👍

2021-08-25 14:44 UTC, merged