[PROJECTS] API EventSource para logs
platiagro/projects pull request #339
Opened 2021-08-23 15:38 UTC by dfvneto

Motivação: existem APIs que são utilizadas em formato polling (consulta periódica). Apesar de fácil de implementar, o polling não é a estratégia mais eficiente (trafega dados mesmo quando não há alterações na API).

Criar os endpoints:

/projects/:id/experiments/:id/logs/eventsource

Handler that returns the generated event source that is responsible for returning logs from given deployment's pod. If the deployment is finished, there's no pod online then being unable to create a log stream 

/projects/:id/deployments/:id/:task_name/logs/eventsource

Since we can currently watch only one pod at a time, the handler needs to receive the task name because an experiment may have more than one task and each task generates one pod.

2021-08-23 17:48 UTC, andreluiz27 requested changes

2021-08-23 17:48 UTC, andreluiz27 commented on projects/api/experiments/experiments.py
> +    if len(pods) > 0:
Aqui poderia ser um booleano, algo do tipo if pods. 
_"_1. if not seq:
In Python, empty lists evaluate False, and non-empty lists evaluate True in boolean contexts. Therefore, you can simply treat the list as a predicate returning a Boolean value. This solution is highly Pythonic and recommended by the PEP8 style guide._"_
https://www.techiedelight.com/check-list-empty-python/

2021-08-24 12:02 UTC, fberanizo requested changes
@dfvneto vou dar checkout na branch e testar umas coisas para tentar evitar o task_name.
Enquanto isso, veja os comentários abaixo, por favor:

2021-08-24 14:05 UTC, fberanizo approved these changes

2021-08-24 14:06 UTC, fberanizo approved these changes

2021-08-24 14:07 UTC, fberanizo requested changes
coloquei "aprovar" sem querer :P

2021-08-24 14:52 UTC, dfvneto commented on projects/api/experiments/experiments.py
> +import urllib.parse
O pathlib não fui eu que utilizei, por isso não mexi.

2021-08-24 15:07 UTC, dfvneto commented on projects/api/experiments/experiments.py
> +                return EventSourceResponse(stream)
A lista de containers resolve o problema de saber qual o container primariamente. Mas como vou saber de qual pod eu pego a informação? Continuo pesquisando ?

2021-08-24 17:27 UTC, fberanizo commented on projects/api/experiments/experiments.py
> +                return EventSourceResponse(stream)
A informação de todos os pods é importante. 
Serão necessárias várias chamadas de `log_stream`. 1 para cada pod (e cada container) retornado pelo `list_workflow_pods`. 
Veja que usar lista de `EXCLUDE_CONTAINERS` não necessariamente vai deixar apenas 1 container no pod. Aliás, nos de deployment vai deixar pelo menos 2: seldon-container-engine e o container com a tarefa.

2021-08-30 13:59 UTC, dfvneto commented
@fberanizo Como resolve o problema de code coverage do sonar? Eu não entendi ele muito bem.

2021-08-31 20:24 UTC, fberanizo approved these changes

2021-08-31 20:24 UTC, merged