[PROJECTS] Adicionar query ao endpoint de healthcheck
platiagro/projects pull request #344
Opened 2021-08-30 17:01 UTC by dfvneto

2021-08-30 19:57 UTC, andreluiz27 commented on projects/api/healthcheck.py
> +        session.query(sqlalchemy.false()).filter(sqlalchemy.false()).all()
Boa tarde Domingos!!, entendi a ideia por trás dessa rota, ficou bem legal, porém fiquei com uma dúvida e uma curiosidade em relação a essa rota:

Dúvida: Qual foi a motivação de usar def e não a forma assíncrona async def ?
Curiosidade: O que sqlalchemy.false() faz ? Tentei olhar a documentação mas não sei se entendi ainda.

2021-08-31 14:01 UTC, dfvneto commented on projects/api/healthcheck.py
> +        session.query(sqlalchemy.false()).filter(sqlalchemy.false()).all()
Eu não usei async por causa do tempo de resposta que estava alto, ele ficava travado nesse método e quando eu tirei o async diminuiu. O false serve para fazer um select vazio no sql alchemy, porque o query e o filter precisam receber parâmetro. Da pra também retornar um modelo vazio no query passando a classe do modelo no parâmetro do query. Eu precisava fazer uma chamada ao banco para testar a conexão dele, por isso a chamada foi feita dessa forma e como o select é vazio ele tem a tendencia de ser uma chamada bem rápida.

2021-08-31 17:49 UTC, fberanizo requested changes
@dfvneto pode adicionar esse endpoint no swagger.yaml também, por favor? :)

2021-08-31 17:49 UTC, fberanizo commented on projects/api/healthcheck.py
> +    return "Sucessfully connected to db"
@dfvneto alguns warnings do flake8:
```
projects/api/healthcheck.py:5:1: F401 'fastapi.Request' imported but unused
projects/api/healthcheck.py:7:1: F401 'sqlalchemy.select' imported but unused
projects/api/healthcheck.py:24:41: W292 no newline at end of file
```

2021-08-31 17:49 UTC, fberanizo commented on projects/api/main.py
>  @app.get("/", response_class=PlainTextResponse)
flake8
```
projects/api/main.py:60:1: E302 expected 2 blank lines, found 1
```

2021-08-31 20:25 UTC, fberanizo approved these changes
👍

2021-08-31 21:24 UTC, merged