Conexão deve se manter aberta
platiagro/projects pull request #347
Opened 2021-09-06 04:01 UTC by dfvneto

Correção para conexão se manter aberta mesmo que não haja pod online na hora da abertura

2021-09-06 04:06 UTC, dfvneto commented
Não sei se é possível, mas o que acontecerá se um pod nunca existir para o determinado experiment ou deployment?

2021-09-08 13:33 UTC, fberanizo requested changes
@dfvneto funcionalmente parece okay :) (tirando o comentário sobre o uso em experimentos)

Por favor, veja só os ajustes de organização/complexidade de código.

2021-09-08 13:33 UTC, fberanizo commented on projects/controllers/logs/logs.py
> +                )
olá, @dfvneto 
o sonar deixou um comentário que esta função está muito complexa:
https://sonarcloud.io/project/issues?id=platiagro_projects&open=AXu5WHW0TpvN1ajWic32&pullRequest=347&resolved=false&types=CODE_SMELL
![image](https://user-images.githubusercontent.com/1791381/132515552-adb85952-2230-4c9f-a4a8-1a34e67a59db.png)

Tenho uma sugestão:
estes trechos estão duplicados:
https://github.com/platiagro/projects/blob/5ad9b183c60f3508bf6addb451def11ce97730af/projects/controllers/logs/logs.py#L53-L73
https://github.com/platiagro/projects/blob/5ad9b183c60f3508bf6addb451def11ce97730af/projects/controllers/logs/logs.py#L272-L289

### Que tal criar uma mesma função para ambos? Ajuda a diminuir a complexidade da função `event_logs(...)` e fica um pouco mais sucinto.

2021-09-08 13:33 UTC, fberanizo commented on projects/controllers/logs/logs.py
> +                pass
@dfvneto talvez seja bom colocar alguma espera aqui... senão pode entrar num loop muito rápido e consumir muitos recursos da máquina.
Que tal fazer como o urllib3 que implementa um`backoff_factor` (sleep progressivo até um valor limite):
https://github.com/urllib3/urllib3/blob/b4321fb5010b8e283c010205c86fa4258993fe44/src/urllib3/util/retry.py#L333-L337
https://github.com/urllib3/urllib3/blob/b4321fb5010b8e283c010205c86fa4258993fe44/src/urllib3/util/retry.py#L281-L296
https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html

2021-09-08 13:33 UTC, fberanizo commented on projects/controllers/logs/logs.py
> +                return merge(iterators)
@dfvneto (acho que já conversamos sobre isso antes) para experimentos essa solução não funciona bem :(
Os pods são criados conforme o fluxo avança, e uma vez que e entra no loop `for pod in pods` novos pods não irão aparecer nos logs (a menos que se reabra a conexão.

**Tudo bem deixar assim, por enquanto.** Na próxima sprint, melhoramos a API para que a lista de iterators seja dinâmica, conforme os pods/containers são criados.

2021-10-18 19:36 UTC, andreluiz27 commented on projects/api/experiments/experiments.py
> +    req : Request
Boa tarde Domingos, entendi a ideia da variável 'req', entretanto, nomes mais intuitivos sempre acrescentam qualidade na leitura do código, o manual de clean code sugere evitar abreviações ou nomes reduzidos.

2021-10-18 19:36 UTC, andreluiz27 commented on projects/controllers/logs/logs.py
> +            """
Vi aqui que optou por não usar logging e por istou permitiu o código passar direto nesse trecho. Entretanto, será que talvez usar logging ainda pudesse ser útil para podermos verificar o andamento das coisas ?

2021-10-19 16:53 UTC, fberanizo commented on projects/controllers/logs/logs.py
> +                                label_selector=f"workflows.argoproj.io/workflow={workflow_name}"):
@dfvneto o eventsource de experimento precisa usar um outro label com base no `experiment_id`. Com o `workflow_name` a solução não funciona quando você clica em executar o fluxo (um novo workflow_name é gerado).

Você pode: adicionar um `pod_label` no container_op:
```python
container_op.add_pod_label("experiment-id", experiment_id)
```
https://github.com/platiagro/projects/blob/ce3e296b79f9343dc8e5fe69663f4f2d37ef0590/projects/kfp/pipeline.py#L61-L64
https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.dsl.html#kfp.dsl.BaseOp.add_pod_label

remover o `workflows = list_workflows(run_id)`

e trocar o `label_selector=f"experiment-id={experiment_id}"`

2021-10-20 03:27 UTC, dfvneto commented on projects/api/experiments/experiments.py
> +    req : Request
Você acabou me atentando para outra coisa, essa variável não está sendo mais utilizada

2021-10-20 03:46 UTC, dfvneto commented on projects/controllers/logs/logs.py
> +                                label_selector=f"workflows.argoproj.io/workflow={workflow_name}"):
Eu fiz as alterações, mas para testar precisa implementar a solução em algum ambiente de teste.

2021-11-22 14:44 UTC, dfvneto commented
Esse pull request vai ser fechado com bugs conhecidos. 

Os bugs serão revistos e resolvidos em futuras iterações.

Atualmente existem dois conhecidos e altamente impactantes:
1) As threads utilizadas para geração dos logs não são fechadas quando a requisição é encerrada pelo cliente.
- Os caminhos das requisições são projects/<project_id>/experiments/<experiment_id>/logs/eventsource e projects/<project_id>/deployments/<deployments_id>/logs/eventsource


![image](https://user-images.githubusercontent.com/30246766/142872035-b173d3c9-f6ab-49a4-9050-2c25d6c2a41a.png)
Imagem 1.
- Na imagem 1 observa-se como está atualmente sendo feito o encerramento das threads por motivo desconhecido.
- Utilizando esse método as threads não estão sendo encerradas.

![image](https://user-images.githubusercontent.com/30246766/142875315-3e6ff8b1-f7f9-4944-92c3-9c9b290a359b.png)
Imagem 2


- A imagem 2 mostra uma das possibilidades que foram testadas e que não funcionaram, pois quando usamos `loop.run_in_executor` (que é como está sendo feito atualmente para gerar as threads) não criamos uma _task_ e sim um `asyncio.future` e estavamos tentando cancelar tratando como _task_.

2) Um pod que foi encontrado pelo worker de pods pode não ser encontrado pelo worker de logs no caso de experimentos. É necessário seguir com estudos sobre porque isso acontece. Foi sugerido checar se o pod precisa estar em algum estado específico pra que o log possa ser iniciado, porém não chegou a se ter alguma conclusão sobre isso (necessita mais investigaões).

2021-11-22 16:00 UTC, fberanizo approved these changes

2021-11-22 16:01 UTC, merged