WIP:feature/prediction-async-api
platiagro/projects pull request #348
Opened 2021-09-16 18:32 UTC by andreluiz27

2021-09-21 17:47 UTC, andreluiz27 commented on projects/api/predictions.py
> +    return {"prediction_id": prediction_promise_uuid}
Tem um problema lógico, eu optei por salvar no BD somente se a predição ocorrer com sucesso, mas preciso pensar como o cliente vai saber se por algum motivo a predição deu algum erro, talvez eu tenha que salvar no BD antes mesmo da predição começar, pra isto talvez valeria a pena um campo de status no model de predição.

2021-09-21 20:43 UTC, andreluiz27 commented on projects/controllers/predictions.py
> +            request_body=request_body,
Gostaria de saber o que seria esse request_body ? Coloquei pra printar, e foi impresso um json bem grande contendo valores referente ao arquivo, não sei se é o que se espera.

2021-09-22 15:56 UTC, andreluiz27 commented on projects/controllers/predictions.py
> +            request = {"foo":"bar"}
Coloquei {"foo":"bar"} por enquanto.

2021-09-22 19:13 UTC, fberanizo commented on projects/api/predictions.py
> +    return {"prediction_id": prediction_promise_uuid}
O cliente saberá que deu erro através do `GET /predictions/:prediction_id`.
Dentro do background_task devemos capturar o erro e salvar no banco. (Talvez seja interessante salvar o `status_code` também :x

---
Acho que vale a pena criar o schema, sim. E de fato, acho que o schema pode ser um `class PredictionCreate`, que não possui o
`request_body` e `response_body`, apenas os outros campos que o `model.Prediction` possui.

2021-09-22 19:14 UTC, fberanizo commented on projects/controllers/deployments/deployments.py
> +        self.template_controller = TemplateController(
Tudo bem. Eventualmente todos códigos serão reformatados :)

2021-09-22 19:14 UTC, fberanizo commented on projects/controllers/predictions.py
> +        project_id: str,
Okay! Pode remover sim, sem problemas;

2021-09-22 19:24 UTC, fberanizo commented on projects/controllers/predictions.py
> +            request_body=request_body,
O `request_body` é o JSON que é enviado para o seldondeployment com as colunas que o modelo precisa receber.
O conteúdo do JSON varia do tipo de dado que vc fez upload.
Um CSV segue o formato:
`{"data":{"ndarray":[ ["uma", "linha", "do", csv"], ["outra", "linha", "do", "csv"]], "names": ["header","do","csv"] }}`
Uma imagem segue outro formato:
`{"binData":"imagem_em_base64"}`
Textos segue outro formato:
`{"strData":"aqui um texto qquer"}`

A documentação do SeldonCore dá mais detalhes:
https://docs.seldon.io/projects/seldon-core/en/v1.8.0/workflow/serving.html#generated-documentation-swagger-ui


**O `response_body` também vai ter o mesmo formato!**

2021-09-22 19:46 UTC, fberanizo commented on projects/controllers/predictions.py
> +            request_body=request_body,
ah, sendo mais prático:
o request_body é a variável que hoje se chama `request`: https://github.com/platiagro/projects/blob/511e8cf450db56a45db580893065e2885c3027a7/projects/controllers/predictions.py#L54-L61

2021-09-22 19:48 UTC, fberanizo commented on projects/controllers/predictions.py
> +            request = {"foo":"bar"}
Agora que você já sabe o que é o request_body, pode trocar :)

2021-09-22 19:52 UTC, fberanizo commented on projects/controllers/predictions.py
> +            self.create_prediction_database_object(
hmmmm não entendi porque "tá rodando em segundo plano". 
Não vi usando o `background_tasks.add_task(...)`.

2021-09-22 19:54 UTC, fberanizo commented on projects/controllers/predictions.py
> +                deployment_id,
Eu prefiro os parâmetros nomeados (mas é só questão de preferência mesmo):
```
self.create_prediction_database_object(
                prediction_id,
                deployment_id,
                request,
                response_content_json,
            )
```

2021-09-22 20:38 UTC, fberanizo requested changes
@andreluiz27 não são muitos ajustes que faltam não.
Acho que dá pra terminar até amanhã (23/09). Aí na próx. sprint só nos concentramos no GET /predictions/:id :)

2021-09-22 20:38 UTC, fberanizo commented on projects/controllers/predictions.py
@andreluiz27 alguns warnings do flake8 que precisam ser ajustados:
```
projects/controllers/predictions.py:4:1: F401 'asyncio' imported but unused
projects/controllers/predictions.py:6:1: F401 'requests.api.request' imported but unused
projects/controllers/predictions.py:7:1: F401 'projects.models.deployment' imported but unused
projects/controllers/predictions.py:7:1: F401 'projects.models.response' imported but unused
projects/controllers/predictions.py:21:1: F401 'time' imported but unused
projects/controllers/predictions.py:54:13: F811 redefinition of unused 'request' from line 6
projects/controllers/predictions.py:70:9: F811 redefinition of unused 'response' from line 7
projects/controllers/predictions.py:74:29: E231 missing whitespace after ':'
```

2021-09-22 20:38 UTC, fberanizo commented on projects/controllers/predictions.py
> +    ):
@andreluiz27 precisa usar o `background_task.add_task` para ficar realmente assíncrono.
Outra possibilidade é trocar o `requests.post` pela lib `httpx` (aliás, este é um desejo antigo, meu) :]

2021-09-22 20:38 UTC, fberanizo commented on projects/models/__init__.py
> +from .predictions import Prediction
@andreluiz27 um detalhe: Todos os arquivos de model estão no singular (sem o 's' no fim). O predictions que foi criado está no plural. Tente deixar igual, por favor. :)

2021-09-22 20:38 UTC, fberanizo commented on projects/models/predictions.py
> +"""Operator model."""
@andreluiz27  acho que sobrou um "Operator" aqui. Era pra ser "Prediction", não?

2021-10-01 12:39 UTC, andreluiz27 commented on .github/workflows/ci.yml
> +        coverage run --branch --source=projects -m pytest tests/test_api.py tests/test_comparisons.py tests/test_data.py tests/test_database.py tests/test_deployments_runs.py tests/test_deployments.p
Adicionei o teste aqui na cobertura

2021-10-01 12:39 UTC, andreluiz27 commented on docs/swagger.yaml
> -        - $ref: "#/components/schemas/Data"
Tirei essa parte aqui, mas acredito que teremos que usar quando tivermos que pegar o arquivo da predição

2021-10-01 12:39 UTC, andreluiz27 commented on docs/swagger.yaml
> -          examples:
Devido o retorno não ser o arquivo de predição e sim as info sobre eu mudei o example no response do swagger

2021-10-01 12:39 UTC, andreluiz27 commented on projects.code-workspace
> +			},
Aqui eu pensei e deixar escrito a possibilidade de usar o debug junto com o pytest, essa adição não faz parte da feature mas resolvi colocar, gostaria de saber se é um boa ideia.

2021-10-01 12:39 UTC, andreluiz27 commented on projects/api/predictions.py
> +@router.post("", response_model=Prediction)
Me pergunto se ficaria melhor colocar o path inteiro, algo do tipo schemas.prediction.Prediction

2021-10-01 12:39 UTC, andreluiz27 commented on projects/controllers/predictions.py
> +        prediction_as_schema = {
Não sei se esse nome de variável ficou bom, porque não é um schema em si e sim um dicionário na forma de um schemas.prediction.Prediction

2021-10-01 12:39 UTC, andreluiz27 commented on projects/controllers/predictions.py
> +        self.background_tasks.add_task(
A parte do código que pega a predição do seldon foi modularizada em outra função e jogada pra rodar como background_tasks

2021-10-01 12:39 UTC, andreluiz27 commented on projects/schemas/prediction.py
> +# -*- coding: utf-8 -*-
Optei, por sugestão do @fberanizo  em criar um schema para a predição

2021-10-01 12:39 UTC, andreluiz27 commented on tests/test_predictions.py
> +        for key in EXPECTED_KEYS_IN_PREDICTION_RESPONSE:
Estou certificando agora se as chaves estão batendo com o esperado

2021-10-01 12:58 UTC, andreluiz27 commented on projects/controllers/predictions.py
> +            prediction_object.status = "failed"
Será que seria melhor deixar esses status como uma constante em forma de dicionário?

2021-10-01 13:22 UTC, fberanizo commented on docs/swagger.yaml
> -          examples:
Okay! Apenas se lembre de recuperar esses valores pra documentação da próxima tarefa (GET /predictions/:id)

2021-10-01 13:58 UTC, fberanizo requested changes
@andreluiz27 só restaram alguma sugestões de organização e documentação:

2021-10-01 13:58 UTC, fberanizo commented on docs/swagger.yaml
> +          type: string
@andreluiz27 é importante descrever quais os status válidos pro pessoal do frontend consumir.
Aqui pode ser usado um `enum: [started, success, error]` por exemplo

2021-10-01 13:58 UTC, fberanizo commented on projects/api/predictions.py
> +@router.post("", response_model=Prediction)
`schemas.prediction.Prediction` ajudar a diferenciar que caso você tenha importado um `models.prediction.Prediction`. Mas aqui neste caso não tem import de models, então não faz tanta diferença. :)

2021-10-01 13:58 UTC, fberanizo commented on projects/controllers/predictions.py
> +        prediction_as_schema = {
hmmm, de fato, aqui é um dicionário então o nome não ficou legal. Se vc quiser retornar um `schema.Prediction`, crie um objeto:
```
prediction_as_schema = Prediction(
    uuid=prediction_object.uuid,
    deployment_id=prediction_object.deployment_id,
    status=prediction_object.status,
)
```

Se você reparar, em outros controller esse tipo de tarefa é feito em uma função `NomeDoSchema.from_orm(model)` dentro do schema:
https://github.com/platiagro/projects/blob/0c13be9cd6aaef63f41b558171f5d688d5f9fb35/projects/schemas/project.py#L31-L56
https://github.com/platiagro/projects/blob/0c13be9cd6aaef63f41b558171f5d688d5f9fb35/projects/controllers/projects.py#L142
---
Aqui ficaria +- assim:
```
prediction_as_schema = schemas.prediction.Prediction.from_orm(prediction_object)
```

e lá no schema:
 ```
class Prediction(BaseModel):
    uuid: str
    deployment_id: str
    status: str

    @classmethod
    def from_orm(cls, model):
        return Prediction(
            uuid=model.uuid,
            deployment_id=model.deployment_id,
            status=model.status,
        )
 ```

2021-10-01 13:58 UTC, fberanizo commented on projects/controllers/predictions.py
> +        self.session.commit()
@andreluiz27 tenho alguns comentários aqui:
`raise InternalServerError` não tem impacto em uma `BrackgroundTask`, uma vez que a resposta já foi enviada ao servidor. Você pode substituir por uma mensagem de `logging.info()`.
---
`prediction_object.response_body = json.dumps(response_content_json)`
não precisa fazer o `json.loads(response._content)`, pode salvar o `response._content` diretamente. Desta forma salvamos os erros também (que são importantes para consulta).

Acredito que usar `success` fica mais claro que `done`. Done pode passar uma impressão de terminado (com erro ou falha).

---
Na minha cabeça este trecho de código faria um "update set response = '..', status = '...' where uuid = '...'"
Você acabou fazendo diferente (e ficou legal)! Só vou colocar num ambiente pra testar e confirmar se está okay. :)

2021-10-01 19:14 UTC, andreluiz27 commented on projects/controllers/predictions.py
> +        self.session.commit()
Fico feliz que tenha gostado xD, pensei que como já tenho a referência do objeto no banco de dados, resolvi utilizá-la pra atualizar em vez de fazer uma busca no BD.

2021-10-04 12:43 UTC, fberanizo approved these changes
👍 Testado com sucesso no amb. 49
![image](https://user-images.githubusercontent.com/1791381/135853384-0a76b172-b280-4586-92f2-9afe60611da3.png)

2021-10-04 12:43 UTC, merged