feature/task-creation-as-container
platiagro/projects pull request #356
Opened 2021-10-27 12:53 UTC by andreluiz27

The idea of this branch is to implement a new way to create tasks. Nowadays, task creation is handled using background tasks, but this leads to some problems, like the bug of missing content after copy. That being said, this pull request will try to make task creation as  container job.

2021-11-03 11:19 UTC, fberanizo commented on projects/kfp/tasks.py
> +    @dsl.pipeline(
O decorador define o pipeline. Dentro da função decorada ficam os componentes do pipeline.

2021-11-03 11:22 UTC, fberanizo commented on projects/kfp/tasks.py
> +        volume_op_task = create_volume_op(name=f"task-{task.uuid}", namespace=namespace)
Isso. O volume é criado para armazenar o conteúdo da tarefa: os notebooks .ipynb, arquivos .py e qualquer outro arquivo que você queira colocar na tarefa.

2021-11-03 11:28 UTC, fberanizo commented on projects/kfp/tasks.py
> +def create_init_task_container_op(
`create_init_task_container_op` é uma "standalone function", sim.
Também há varias outras "standalone functions" definidas aqui: `create_configmap_op`, `patch_notebook_volume_mounts_op`, `create_volume_op` etc. 

Em geral eu segui um padrão de nomenclatura e todo "standalone function" termina com `_op`.

2021-11-03 11:50 UTC, fberanizo commented on projects/kfp/tasks.py
> +    args = ["--task-id", task.uuid, "--destination", DESTINATION_TASK_VOLUME_MOUNT_PATH]
É essa a ideia, sim. São argumentos passados para um container que roda o comando `python -m projects.init_task.main`.
O main.py é este arquivo (que usa os argumentos):
https://github.com/platiagro/projects/blob/d6c8ea7634e76704c42b7e92a7ae19499941b596/projects/init_task/main.py#L104-L133

E o container usa a imagem docker definida na variável `INIT_TASK_CONTAINER_IMAGE` que foi buildada com este Dockerfile:
https://github.com/platiagro/projects/blob/feature/kfp-refactor/Dockerfile.inittask

2021-11-03 11:55 UTC, fberanizo commented on projects/kfp/tasks.py
> +                "image": INIT_TASK_CONTAINER_IMAGE,
Isso! Acredito que aquele Dockerfile e main.py que mencionei na mensagem NÃO são mais necessários (porque só precisamos copiar o conteúdo da tarefa para dentro do volume, e um `cp -R /origem /destino` deve ser suficiente).

Então pode substituir o  `f"platiagro/init-task:{__version__}-SNAPSHOT"` por uma imagem do alpine.

2021-11-03 12:00 UTC, fberanizo commented on projects/kfp/tasks.py
> +    func = load_component_from_text(text)
Hmmm, sim.
Todo componente precisa definir uma imagem docker (e o comando e argumentos são opcionais). Neste caso os argumentos são usados pra:
`--experiment-notebook` e `--deployment-notebook` são os conteúdos de notebooks em "branco". No caso de criar uma tarefa em branco.

`--source` é o caminho para o volume da tarefa a ser copiada. No caso de criar uma tarefa a partir de uma cópia de tarefa existente.

`--destination` é o caminho para o volume da tarefa criada.

2021-11-30 16:49 UTC, dfvneto requested changes

2021-11-30 16:49 UTC, dfvneto commented on projects/kfp/tasks.py
> +        "inputs": [],
https://www.kubeflow.org/docs/components/pipelines/sdk/component-development/
Link falando sobre o uso de componentes de dos inputs. Recomendo utilizar os inputs na hora de criar o command

2021-12-01 01:28 UTC, dfvneto commented
Tomar cuidado com os arquivos de teste gerado. Acredito que o arquivo test.db tenha sido gerado no lugar errado. Tem uma pasta chamada [resources](https://github.com/platiagro/projects/tree/deletion-as-container-job/tests/resources) na pasta de testes, acredito que ele pertença la.

2021-12-01 01:31 UTC, dfvneto commented on tests/test_tasks.py
> +    make_task_creation_job,
essa linha está sendo importada duas vezes

2021-12-01 18:57 UTC, merged