Feature/send email on delete
platiagro/projects pull request #361
Opened 2021-11-26 12:57 UTC by dfvneto

O objetivo dessa feature é que sejam enviado emails através da platiagro.

2021-11-30 13:57 UTC, andreluiz27 requested changes
Vi o código, parece estar okay. Tem um print que veio da minha branch perdido por aí rs. Outro ponto, que é desejável ter a cobertura de teste de >80%.

2021-11-30 13:57 UTC, andreluiz27 commented on projects/kfp/tasks.py
> +        print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
haha tem esse print que veio da minha branch aqui

2021-12-10 14:13 UTC, dfvneto commented
atividade Relacionada a PLATIA-2268

2022-01-19 05:42 UTC, dfvneto commented
Falta só resolver o problema de segurança, aceito sugestões

2022-01-21 10:54 UTC, andreluiz27 approved these changes

2022-01-21 13:28 UTC, alanmsant2 approved these changes

2022-01-25 13:53 UTC, merged