Added timezone in the timestamp of projects, experiments and deployments
platiagro/projects pull request #363
Opened 2021-12-01 02:48 UTC by dfvneto

Reprodução:

Implantar um fluxo (com computador no horário de brasília)
Resultado (foto em anexo)

No canto superior o horário local, e no campo “Data de criação”, 3 horas adiantado)

 

ANÁLISE DE ERRO: 
O backend da plataforma retorna as datas no fuso "UTC", porém usa formatação errada, pois a hora não termina com "Z" ou "+00:00".

DESIGN DE SOLUÇÃO:
Adicionar a informação de timezone ("Z" ou "+00:00" nos atributos updated_at e created_at nas APIs.

2021-12-06 19:20 UTC, andreluiz27 requested changes

2021-12-06 19:20 UTC, andreluiz27 commented on projects/models/comparison.py
> +    now = datetime.utcnow().replace(tzinfo=timezone.utc)
Entendi a lógica utilizada, achei válida. Entretanto, me permita algumas observações pertinentes: 
Talvez o trecho 'now = datetime.utcnow().replace(tzinfo=timezone.utc)' esteja num lugar não coerente, pois esse valor não é uma instância de Column, então não será armazenada no banco de dados, e de fato, nem era pra ser.

O que eu faria: 

class Comparison(Base):
    __tablename__ = "comparisons"
    uuid = Column(String(255), primary_key=True)
    project_id = Column(String(255), ForeignKey("projects.uuid"), nullable=False, index=True)
    experiment_id = Column(String(255), ForeignKey("experiments.uuid"), index=True)
    operator_id = Column(String(255), index=True)
    active_tab = Column(String(10), nullable=False, default='1')
    run_id = Column(String(255))
    layout = Column(JSON)
    created_at = Column(TimeStamp(), nullable=False, default=now)
    updated_at = Column(TimeStamp(), nullable=False, default=now)

    def now():
        return datetime.utcnow().replace(tzinfo=timezone.utc)

2021-12-07 13:13 UTC, andreluiz27 approved these changes

2021-12-09 14:41 UTC, alanmsant2 approved these changes

2021-12-10 13:18 UTC, merged