task listing with validation and now as POST
platiagro/projects pull request #388
Opened 2022-03-28 21:07 UTC by andreluiz27

2022-03-30 14:53 UTC, dfvneto requested changes

2022-03-30 14:53 UTC, dfvneto commented on projects/api/tasks/tasks.py
> +@router.post("/listtasks", response_model=projects.schemas.task.TaskList)
adicionar um underline aqui para melhorara a leitura do path da requisição

2022-03-30 14:57 UTC, dfvneto approved these changes

2022-03-30 15:04 UTC, dfvneto commented on projects/api/tasks/tasks.py
> +@router.post("/listtasks", response_model=projects.schemas.task.TaskList)
adicionei o hífen mesmo porque é a norma das melhores práticas

2022-03-30 18:52 UTC, andreluiz27 commented on projects/api/tasks/tasks.py
> +@router.post("/listtasks", response_model=projects.schemas.task.TaskList)
Todas as rotas estão escrita com esse import, apenas seguir o padrão de escrita do código.

2022-03-30 18:52 UTC, andreluiz27 commented on projects/api/tasks/tasks.py
> +    request_schema: projects.schemas.task.TaskListRequest,
Todas as rotas estão escrita com esse import, apenas seguir o padrão de escrita do código.

2022-03-30 18:52 UTC, andreluiz27 commented on projects/api/tasks/tasks.py
> +@router.post("/listtasks", response_model=projects.schemas.task.TaskList)
Todas as rotas estão escrita com esse import, apenas seguir o padrão de escrita do código.

2022-03-31 12:40 UTC, alanmsant2 approved these changes

2022-03-31 13:34 UTC, merged